# Generated by Django 4.1.7 on 2023-04-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('des', models.TextField(max_length=255)),
                ('categories', models.CharField(choices=[('deodar', 'deodar'), ('oak', 'oak'), ('Mahogany', 'Mahogany'), ('sal', 'sal')], max_length=150)),
                ('pic', models.FileField(default='deodar.jpeg', upload_to='blog_photos')),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
